CREATE TABLE FILES(
ID NUMBER,
FILE_NAME NVARCHAR2(50) NOT NULL,
FILE_FORMAT NVARCHAR2(10) NOT NULL,
FILE_SIZE NUMBER NOT NULL,
STORAGE_ID NUMBER,
CONSTRAINT FILE_ID PRIMARY KEY(ID),
CONSTRAINT STORAGE_ID_FK FOREIGN KEY(STORAGE_ID) REFERENCES STORAGES(ID)
);