CREATE TABLE ORDERS(
ID NUMBER NOT NULL,
ORDER_USER_ID NUMBER,
ORDER_ROOM_ID NUMBER,
ORDER_DATE_FROM TIMESTAMP,
ORDER_DATE_TO TIMESTAMP,
ORDER_MONEY_PAID NUMBER,
CONSTRAINT ORDER_ID PRIMARY KEY(ID),
CONSTRAINT ORDER_USER_FK FOREIGN KEY(ORDER_USER_ID) REFERENCES USERS(ID),
CONSTRAINT ORDER_ROOM_FK FOREIGN KEY(ORDER_ROOM_ID) REFERENCES ROOMS(ID)
);









